---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "postimit"
  DB_USER: "postgres"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOG_LEVEL: "INFO"