---
apiVersion: v1
kind: Service
metadata:
  name: daphne
  namespace: default
  labels:
    app: daphne
spec:
  type: NodePort
  selector:
    app: daphne
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30081